### ISSUE TITLE
grad3 todo list

### ISSUE THREAD

**Issue by Ionizing** [IonizingRadiation/usefultools-for-vasp#1]
# Todo list:

- [x] improve arguments parsing;
- [x] add index output for the atom with `Max|F|`;
- [x] lower the accuracy of `log|dE|`, 1 decimal point is enough;
- [x] add option for outputing `Vol.` , disabled by default;
- [x] add option for outputing `mag`, disabled by default;
- [x] add direction labels of `max|F|`, 1 meV is enough;
- [x] lower the accuracy of Energy;
- [x] bugfix to output `mag` occasionally.

**Comment by Ionizing** [comment]
All done
